#!/usr/bin/env python3
"""
Ovule-gated pollen competition and passenger reproductive isolation.

This script is a deliberately transparent simulation sandbox. It is not meant
as a final inference engine. It asks when a simple mechanism is recoverable:

    ovule number -> K = effective pollen load / ovule number
    -> pollen competition -> maternal filtering -> directional prezygotic RI

The script can:
  1. simulate an ultrametric phylogeny using a simple coalescent tree,
  2. simulate few- and many-ovule states on that tree,
  3. generate effective pollen load under a scaling model,
  4. compute K, pollen competition, sweeps, maternal filters,
  5. simulate prezygotic and postzygotic reproductive isolation,
  6. impose different empirical data structures,
  7. summarise whether reciprocal asymmetry recovers delta log(K).

Dependencies: numpy, pandas, scipy, matplotlib.

Example:
    python simulate_ovule_gated_RI.py --outdir ../results_demo --quick

Author: Daniel Ortiz-Barrientos project sandbox; generated with CG.
"""

from __future__ import annotations

import argparse
import itertools
import math
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd

try:
    from scipy.stats import norm
except Exception as exc:  # pragma: no cover
    raise RuntimeError("This script requires scipy. Install with: pip install scipy") from exc

try:
    import matplotlib.pyplot as plt
except Exception as exc:  # pragma: no cover
    raise RuntimeError("This script requires matplotlib. Install with: pip install matplotlib") from exc


# -----------------------------------------------------------------------------
# Tree simulation
# -----------------------------------------------------------------------------

@dataclass
class Node:
    """A node in a simple ultrametric tree.

    We build the tree backwards from present-day tips using a coalescent-like
    process. Tip height is 0; the root has the largest height. Branch length
    from parent to child is parent.height - child.height.
    """

    node_id: int
    height: float
    children: List[int] = field(default_factory=list)
    parent: Optional[int] = None


def simulate_coalescent_tree(n_tips: int, rng: np.random.Generator) -> Tuple[Dict[int, Node], int, List[int]]:
    """Simulate a simple ultrametric binary tree.

    The topology is random and branch lengths are generated by waiting times
    proportional to the number of possible coalescent pairs. Heights are scaled
    so that the root height is one.
    """

    if n_tips < 2:
        raise ValueError("n_tips must be at least 2")

    nodes: Dict[int, Node] = {i: Node(node_id=i, height=0.0) for i in range(n_tips)}
    active = list(range(n_tips))
    next_id = n_tips
    current_height = 0.0

    while len(active) > 1:
        k = len(active)
        rate = k * (k - 1) / 2.0
        current_height += rng.exponential(1.0 / rate)
        a, b = rng.choice(active, size=2, replace=False)
        parent = Node(node_id=next_id, height=current_height, children=[int(a), int(b)])
        nodes[next_id] = parent
        nodes[int(a)].parent = next_id
        nodes[int(b)].parent = next_id
        active = [x for x in active if x not in (a, b)]
        active.append(next_id)
        next_id += 1

    root_id = active[0]
    root_height = nodes[root_id].height
    if root_height <= 0:
        raise RuntimeError("Tree root height was zero; this should not happen.")

    # Normalise heights to root height = 1.
    for node in nodes.values():
        node.height /= root_height

    tip_ids = list(range(n_tips))
    return nodes, root_id, tip_ids


def ancestors(nodes: Dict[int, Node], tip_id: int) -> Dict[int, float]:
    """Return ancestor nodes and their heights for one tip, including the tip."""

    out: Dict[int, float] = {}
    current = tip_id
    while current is not None:
        out[current] = nodes[current].height
        current = nodes[current].parent
    return out


def pairwise_mrca_heights(nodes: Dict[int, Node], tip_ids: List[int]) -> pd.DataFrame:
    """Calculate pairwise MRCA heights for all unordered tip pairs."""

    ancestor_maps = {tip: ancestors(nodes, tip) for tip in tip_ids}
    records = []
    for i, j in itertools.combinations(tip_ids, 2):
        common = set(ancestor_maps[i]).intersection(ancestor_maps[j])
        # In this backward-time representation, the MRCA is the common ancestor
        # with the smallest height greater than zero that is shared by the pair.
        # Because root height is largest and tips are zero, min positive common
        # is the most recent shared ancestor.
        mrca_height = min(ancestor_maps[i][a] for a in common if ancestor_maps[i][a] > 0)
        records.append({"i": i, "j": j, "divergence_time": mrca_height})
    return pd.DataFrame.from_records(records)


def simulate_brownian_trait(
    nodes: Dict[int, Node],
    root_id: int,
    tip_ids: List[int],
    rng: np.random.Generator,
    root_value: float = 0.0,
    sigma: float = 1.0,
) -> Dict[int, float]:
    """Simulate a Brownian trait down the tree and return tip values."""

    values: Dict[int, float] = {root_id: root_value}
    stack = [root_id]
    while stack:
        parent = stack.pop()
        for child in nodes[parent].children:
            bl = nodes[parent].height - nodes[child].height
            values[child] = values[parent] + rng.normal(0.0, sigma * math.sqrt(max(bl, 0.0)))
            stack.append(child)
    return {tip: values[tip] for tip in tip_ids}


def simulate_two_state_trait(
    nodes: Dict[int, Node],
    root_id: int,
    tip_ids: List[int],
    rng: np.random.Generator,
    q: float = 2.0,
    root_state: int = 0,
) -> Dict[int, int]:
    """Simulate a symmetric two-state trait on the tree.

    State 0 = many ovules; state 1 = few ovules.
    For a symmetric two-state continuous-time Markov chain, the probability of
    a state change over branch length t is 0.5 * (1 - exp(-2 q t)).
    """

    states: Dict[int, int] = {root_id: root_state}
    stack = [root_id]
    while stack:
        parent = stack.pop()
        for child in nodes[parent].children:
            bl = nodes[parent].height - nodes[child].height
            p_switch = 0.5 * (1.0 - math.exp(-2.0 * q * max(bl, 0.0)))
            state = states[parent]
            if rng.random() < p_switch:
                state = 1 - state
            states[child] = state
            stack.append(child)
    return {tip: states[tip] for tip in tip_ids}


# -----------------------------------------------------------------------------
# Biology functions
# -----------------------------------------------------------------------------

def truncation_selection(K: np.ndarray | float, sigma_z: float = 1.0) -> np.ndarray | float:
    """Selection differential among successful pollen grains.

    If K <= 1, no truncation component is imposed. If K > 1, the successful
    pollen grains are the top q = 1/K fraction under a normal performance trait.
    """

    K_arr = np.asarray(K, dtype=float)
    out = np.zeros_like(K_arr)
    mask = K_arr > 1.0
    if np.any(mask):
        q = 1.0 / K_arr[mask]
        # Avoid infinite quantiles at numerical extremes.
        q = np.clip(q, 1e-9, 1.0 - 1e-9)
        t = norm.ppf(1.0 - q)
        out[mask] = sigma_z * norm.pdf(t) / q
    if np.ndim(K) == 0:
        return float(out)
    return out


def competition_opportunity(mean_pollen: float, ovules: float, rng: np.random.Generator, theta: float = 5.0, n_flowers: int = 500) -> float:
    """Estimate Omega = E[((P - O)+) / P] under negative-binomial pollen loads."""

    if mean_pollen <= 0 or ovules <= 0:
        return 0.0
    # Negative binomial parameterisation: variance = mu + mu^2/theta.
    # numpy uses n and p, where mean = n(1-p)/p.
    n = theta
    p = theta / (theta + mean_pollen)
    pollen = rng.negative_binomial(n=n, p=p, size=n_flowers).astype(float)
    with np.errstate(divide="ignore", invalid="ignore"):
        omega = np.where(pollen > 0, np.maximum(pollen - ovules, 0.0) / pollen, 0.0)
    return float(np.mean(omega))


def maternal_filter_from_K(
    K: np.ndarray,
    F_min: float = 0.05,
    F_max: float = 2.0,
    half_sat: float = 1.0,
) -> np.ndarray:
    """A smooth monotone approximation to F*(K).

    The LaTeX note gives a mechanistic optimisation model. For simulation we
    use a saturating function that preserves the qualitative result dF*/dK > 0.
    """

    x = np.log1p(np.maximum(K, 0.0))
    return F_min + F_max * x / (x + half_sat)


def beta_binomial_rng(rng: np.random.Generator, n: np.ndarray, p: np.ndarray, rho: float = 0.05) -> np.ndarray:
    """Generate beta-binomial counts with intraclass correlation rho.

    rho close to 0 approaches a binomial. rho > 0 adds overdispersion.
    """

    n = np.asarray(n, dtype=int)
    p = np.clip(np.asarray(p, dtype=float), 1e-6, 1.0 - 1e-6)
    rho = float(np.clip(rho, 1e-6, 0.95))
    phi = (1.0 - rho) / rho
    alpha = p * phi
    beta = (1.0 - p) * phi
    p_draw = rng.beta(alpha, beta)
    return rng.binomial(n, p_draw)


def ols_fit(y: np.ndarray, X: np.ndarray, names: List[str]) -> Dict[str, float]:
    """Small OLS helper returning coefficients and R^2."""

    ok = np.isfinite(y) & np.all(np.isfinite(X), axis=1)
    if ok.sum() <= X.shape[1]:
        return {f"beta_{name}": np.nan for name in names} | {"r2": np.nan, "n": int(ok.sum())}
    y0 = y[ok]
    X0 = X[ok]
    coef, *_ = np.linalg.lstsq(X0, y0, rcond=None)
    fitted = X0 @ coef
    ss_res = float(np.sum((y0 - fitted) ** 2))
    ss_tot = float(np.sum((y0 - np.mean(y0)) ** 2))
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else np.nan
    out = {f"beta_{name}": float(c) for name, c in zip(names, coef)}
    out["r2"] = r2
    out["n"] = int(ok.sum())
    return out


# -----------------------------------------------------------------------------
# Simulation core
# -----------------------------------------------------------------------------

@dataclass
class Scenario:
    n_tips: int = 80
    alpha: float = 0.6
    psi: float = 0.02
    pollen_c: float = 300.0
    pollen_noise: float = 0.35
    architecture: str = "pleiotropic"  # independent, linked, pleiotropic
    recombination: float = 0.01
    pleiotropy: float = 0.75
    state_transition_rate: float = 2.0
    many_log_ovules: float = math.log(200.0)
    few_log_ovules: float = math.log(25.0)
    ovule_residual_sd: float = 0.25
    ovule_brownian_sd: float = 0.20
    filter_noise_sd: float = 0.08
    drift_mismatch_rate: float = 0.30
    selected_mismatch_scale: float = 0.25
    sweep_base: float = 0.05
    sweep_scale: float = 2.50
    post_lambda: float = 3.0
    post_gamma: float = 1.5
    post_h: float = 0.25
    seed_denominator_multiplier: float = 10.0
    beta_binomial_rho: float = 0.05
    post_n: int = 50


def simulate_one_replicate(
    scenario: Scenario,
    rng: np.random.Generator,
    replicate: int = 0,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Simulate one tree, lineage table, and pair table."""

    nodes, root_id, tip_ids = simulate_coalescent_tree(scenario.n_tips, rng)
    div_df = pairwise_mrca_heights(nodes, tip_ids)

    states = simulate_two_state_trait(
        nodes, root_id, tip_ids, rng,
        q=scenario.state_transition_rate,
        root_state=0,
    )
    brownian = simulate_brownian_trait(
        nodes, root_id, tip_ids, rng,
        root_value=0.0,
        sigma=scenario.ovule_brownian_sd,
    )

    records = []
    for tip in tip_ids:
        state = states[tip]
        state_name = "few" if state == 1 else "many"
        theta = scenario.few_log_ovules if state == 1 else scenario.many_log_ovules
        log_ovules = theta + brownian[tip] + rng.normal(0.0, scenario.ovule_residual_sd)
        ovules = max(2.0, float(np.exp(log_ovules)))
        pollen_production = scenario.pollen_c * (ovules ** scenario.alpha) * math.exp(rng.normal(0.0, scenario.pollen_noise))
        pollen_eff = scenario.psi * pollen_production
        K = pollen_eff / ovules
        Sz = truncation_selection(K, sigma_z=1.0)
        beta_z = Sz  # sigma_z = 1, so beta_z = S_z
        sweep_rate = scenario.sweep_base + scenario.sweep_scale * max(beta_z, 0.0)
        sweep_count = rng.poisson(max(sweep_rate, 1e-9))
        omega = competition_opportunity(pollen_eff, ovules, rng)
        filter_F = maternal_filter_from_K(np.array([K]))[0] + rng.normal(0.0, scenario.filter_noise_sd)
        filter_F = max(0.0, filter_F)

        records.append({
            "replicate": replicate,
            "species": f"sp_{tip:03d}",
            "tip_id": tip,
            "state": state_name,
            "ovules": ovules,
            "log_ovules": math.log(ovules),
            "pollen_production": pollen_production,
            "pollen_eff": pollen_eff,
            "psi": scenario.psi,
            "alpha": scenario.alpha,
            "K": K,
            "logK": math.log(max(K, 1e-12)),
            "omega": omega,
            "pollen_selection_Sz": Sz,
            "sweep_count": sweep_count,
            "filter_F": filter_F,
        })

    lineage_df = pd.DataFrame.from_records(records)
    lookup = lineage_df.set_index("tip_id")

    pair_records = []
    for row in div_df.itertuples(index=False):
        i = int(row.i)
        j = int(row.j)
        ti = lookup.loc[i]
        tj = lookup.loc[j]
        T = float(row.divergence_time)

        base_mismatch = scenario.drift_mismatch_rate * T + abs(rng.normal(0.0, 0.03))
        mean_sweeps = 0.5 * (float(ti.sweep_count) + float(tj.sweep_count))
        delta_logK = float(ti.logK - tj.logK)
        mean_selection = 0.5 * (float(ti.pollen_selection_Sz) + float(tj.pollen_selection_Sz))

        if scenario.architecture == "independent":
            arch_coupling = 0.04
        elif scenario.architecture == "linked":
            H = mean_selection / (mean_selection + scenario.recombination + 1e-9)
            arch_coupling = 0.45 * H
        elif scenario.architecture == "pleiotropic":
            arch_coupling = 0.70 * scenario.pleiotropy
        else:
            raise ValueError(f"Unknown architecture: {scenario.architecture}")

        selected_mismatch = scenario.selected_mismatch_scale * arch_coupling * (
            mean_sweeps + 0.5 * abs(delta_logK)
        )
        D = max(0.0, base_mismatch + selected_mismatch)

        F_i = float(ti.filter_F)
        F_j = float(tj.filter_F)
        Rpre_i_from_j = 1.0 - math.exp(-F_i * D)
        Rpre_j_from_i = 1.0 - math.exp(-F_j * D)
        asym = Rpre_i_from_j - Rpre_j_from_i

        B = rng.poisson(max(scenario.post_lambda * (T ** scenario.post_gamma), 0.0))
        Rpost = 1.0 - math.exp(-scenario.post_h * B)

        # Observed seed counts. Denominator scales with maternal ovules and number
        # of flowers crossed, represented by seed_denominator_multiplier.
        N_i = max(1, int(round(float(ti.ovules) * scenario.seed_denominator_multiplier)))
        N_j = max(1, int(round(float(tj.ovules) * scenario.seed_denominator_multiplier)))
        seed_prob_i = np.clip(1.0 - Rpre_i_from_j, 1e-6, 1.0 - 1e-6)
        seed_prob_j = np.clip(1.0 - Rpre_j_from_i, 1e-6, 1.0 - 1e-6)
        seeds_i = beta_binomial_rng(rng, np.array([N_i]), np.array([seed_prob_i]), scenario.beta_binomial_rho)[0]
        seeds_j = beta_binomial_rng(rng, np.array([N_j]), np.array([seed_prob_j]), scenario.beta_binomial_rho)[0]
        post_success = rng.binomial(scenario.post_n, np.clip(1.0 - Rpost, 1e-6, 1.0 - 1e-6))

        pair_records.append({
            "replicate": replicate,
            "species_i": ti.species,
            "species_j": tj.species,
            "tip_i": i,
            "tip_j": j,
            "state_i": ti.state,
            "state_j": tj.state,
            "divergence_time": T,
            "ovules_i": ti.ovules,
            "ovules_j": tj.ovules,
            "logO_i": ti.log_ovules,
            "logO_j": tj.log_ovules,
            "K_i": ti.K,
            "K_j": tj.K,
            "logK_i": ti.logK,
            "logK_j": tj.logK,
            "delta_logK_i_minus_j": delta_logK,
            "delta_logO_j_minus_i": float(tj.log_ovules - ti.log_ovules),
            "filter_i": F_i,
            "filter_j": F_j,
            "mismatch_D": D,
            "Rpre_i_from_j": Rpre_i_from_j,
            "Rpre_j_from_i": Rpre_j_from_i,
            "asym_i_minus_j": asym,
            "Rpost": Rpost,
            "BDM_count": B,
            "N_seed_i_from_j": N_i,
            "N_seed_j_from_i": N_j,
            "seeds_i_from_j": int(seeds_i),
            "seeds_j_from_i": int(seeds_j),
            "observed_Rpre_i_from_j": 1.0 - seeds_i / N_i,
            "observed_Rpre_j_from_i": 1.0 - seeds_j / N_j,
            "observed_asym_i_minus_j": (1.0 - seeds_i / N_i) - (1.0 - seeds_j / N_j),
            "N_post": scenario.post_n,
            "post_success": int(post_success),
            "observed_Rpost": 1.0 - post_success / scenario.post_n,
        })

    pair_df = pd.DataFrame.from_records(pair_records)
    return lineage_df, pair_df


# -----------------------------------------------------------------------------
# Data structure degradation and summaries
# -----------------------------------------------------------------------------

def impose_data_structure(pair_df: pd.DataFrame, structure: str, rng: np.random.Generator, sparse_fraction: float = 0.25) -> pd.DataFrame:
    """Return a modified pair table representing a realistic data structure."""

    df = pair_df.copy()

    if structure == "dense_reciprocal":
        return df

    if structure == "sparse_reciprocal":
        keep = rng.random(len(df)) < sparse_fraction
        return df.loc[keep].reset_index(drop=True)

    if structure == "pi_pairs":
        # A simple greedy approximation: choose pairs without species reuse.
        shuffled = df.sample(frac=1.0, random_state=int(rng.integers(0, 2**31 - 1))).reset_index(drop=True)
        used = set()
        keep_idx = []
        for idx, row in shuffled.iterrows():
            if row.tip_i not in used and row.tip_j not in used:
                keep_idx.append(idx)
                used.add(row.tip_i)
                used.add(row.tip_j)
        return shuffled.loc[keep_idx].reset_index(drop=True)

    if structure == "one_direction":
        # Keep only one direction by deleting observed reciprocal asymmetry.
        # True asymmetry is retained for diagnostics, but observed asymmetry is set missing.
        maternal_i = rng.random(len(df)) < 0.5
        df["observed_Rpre_one_direction"] = np.where(
            maternal_i,
            df["observed_Rpre_i_from_j"],
            df["observed_Rpre_j_from_i"],
        )
        df["maternal_logK_one_direction"] = np.where(maternal_i, df["logK_i"], df["logK_j"])
        df["observed_asym_i_minus_j"] = np.nan
        return df

    if structure == "summary_only":
        # Keep summary RI but lose denominators and raw seed counts.
        drop_cols = [
            "N_seed_i_from_j", "N_seed_j_from_i",
            "seeds_i_from_j", "seeds_j_from_i",
            "N_post", "post_success",
        ]
        return df.drop(columns=[c for c in drop_cols if c in df.columns])

    raise ValueError(f"Unknown data structure: {structure}")


def summarise_recovery(pair_df: pd.DataFrame, structure: str) -> Dict[str, float]:
    """Summarise whether asymmetry recovers delta log(K)."""

    out: Dict[str, float] = {"data_structure": structure}

    if structure == "one_direction":
        y = pair_df["observed_Rpre_one_direction"].to_numpy(dtype=float)
        X = np.column_stack([
            np.ones(len(pair_df)),
            pair_df["maternal_logK_one_direction"].to_numpy(dtype=float),
            pair_df["divergence_time"].to_numpy(dtype=float),
        ])
        res = ols_fit(y, X, ["intercept", "maternal_logK", "divergence_time"])
        out.update(res)
        return out

    y = pair_df["observed_asym_i_minus_j"].to_numpy(dtype=float)
    X = np.column_stack([
        np.ones(len(pair_df)),
        pair_df["delta_logK_i_minus_j"].to_numpy(dtype=float),
        pair_df["divergence_time"].to_numpy(dtype=float),
    ])
    res_k = ols_fit(y, X, ["intercept", "delta_logK", "divergence_time"])
    out.update({f"asym_model_{k}": v for k, v in res_k.items()})

    # Proxy model using ovules only: asymmetry should increase with logO_j - logO_i
    # under alpha < 1 because low O_i implies high K_i.
    Xo = np.column_stack([
        np.ones(len(pair_df)),
        pair_df["delta_logO_j_minus_i"].to_numpy(dtype=float),
        pair_df["divergence_time"].to_numpy(dtype=float),
    ])
    res_o = ols_fit(y, Xo, ["intercept", "delta_logO_proxy", "divergence_time"])
    out.update({f"ovule_proxy_{k}": v for k, v in res_o.items()})

    # Postzygotic contrast: observed Rpost should track divergence time.
    yp = pair_df["observed_Rpost"].to_numpy(dtype=float)
    Xp = np.column_stack([
        np.ones(len(pair_df)),
        pair_df["divergence_time"].to_numpy(dtype=float),
        np.abs(pair_df["delta_logK_i_minus_j"].to_numpy(dtype=float)),
    ])
    res_p = ols_fit(yp, Xp, ["intercept", "divergence_time", "abs_delta_logK"])
    out.update({f"post_model_{k}": v for k, v in res_p.items()})

    return out


def plot_demo(lineage_df: pd.DataFrame, pair_df: pd.DataFrame, outdir: Path) -> None:
    """Write a few simple diagnostic plots."""

    outdir.mkdir(parents=True, exist_ok=True)

    fig = plt.figure(figsize=(6, 4.5))
    ax = fig.add_subplot(111)
    ax.scatter(lineage_df["ovules"], lineage_df["K"], alpha=0.75)
    ax.axhline(1.0, linestyle="--", linewidth=1)
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Ovules per ovary")
    ax.set_ylabel("K = effective pollen load / ovules")
    ax.set_title("Competition state across simulated lineages")
    fig.tight_layout()
    fig.savefig(outdir / "fig_K_vs_ovules.png", dpi=300)
    plt.close(fig)

    fig = plt.figure(figsize=(6, 4.5))
    ax = fig.add_subplot(111)
    ax.scatter(pair_df["delta_logK_i_minus_j"], pair_df["observed_asym_i_minus_j"], alpha=0.35)
    ax.axhline(0.0, linestyle="--", linewidth=1)
    ax.axvline(0.0, linestyle="--", linewidth=1)
    ax.set_xlabel("log(K_i) - log(K_j)")
    ax.set_ylabel("Observed asymmetry: RI(i<-j) - RI(j<-i)")
    ax.set_title("Directional prezygotic RI tracks maternal competition state")
    fig.tight_layout()
    fig.savefig(outdir / "fig_asymmetry_vs_delta_logK.png", dpi=300)
    plt.close(fig)

    fig = plt.figure(figsize=(6, 4.5))
    ax = fig.add_subplot(111)
    ax.scatter(pair_df["divergence_time"], pair_df["observed_Rpost"], alpha=0.35)
    ax.set_xlabel("Divergence time on simulated tree")
    ax.set_ylabel("Observed postzygotic RI")
    ax.set_title("Postzygotic RI as a divergence-time contrast")
    fig.tight_layout()
    fig.savefig(outdir / "fig_postRI_vs_divergence.png", dpi=300)
    plt.close(fig)


def run_grid(args: argparse.Namespace) -> None:
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    rng_master = np.random.default_rng(args.seed)

    if args.quick:
        alphas = [0.6, 1.0, 1.25]
        psis = [0.005, 0.02, 0.05]
        architectures = ["independent", "linked", "pleiotropic"]
        structures = ["dense_reciprocal", "sparse_reciprocal", "pi_pairs", "one_direction", "summary_only"]
        n_reps = min(args.n_reps, 8)
    else:
        alphas = args.alphas
        psis = args.psis
        architectures = args.architectures
        structures = args.data_structures
        n_reps = args.n_reps

    all_summaries: List[Dict[str, float]] = []
    saved_demo = False

    for alpha, psi, arch, rep in itertools.product(alphas, psis, architectures, range(n_reps)):
        scenario = Scenario(
            n_tips=args.n_tips,
            alpha=alpha,
            psi=psi,
            pollen_c=args.pollen_c,
            architecture=arch,
            recombination=args.recombination,
            pleiotropy=args.pleiotropy,
        )
        rng = np.random.default_rng(int(rng_master.integers(0, 2**31 - 1)))
        lineage_df, pair_df = simulate_one_replicate(scenario, rng, replicate=rep)

        if not saved_demo and arch == architectures[-1] and alpha == alphas[0] and abs(psi - 0.02) < 1e-12:
            lineage_df.to_csv(outdir / "demo_lineages.csv", index=False)
            pair_df.to_csv(outdir / "demo_pairs_full.csv", index=False)
            plot_demo(lineage_df, pair_df, outdir)
            saved_demo = True

        for structure in structures:
            degraded = impose_data_structure(pair_df, structure, rng)
            summary = summarise_recovery(degraded, structure)
            summary.update({
                "replicate": rep,
                "alpha": alpha,
                "psi": psi,
                "architecture": arch,
                "n_tips": args.n_tips,
                "mean_K": float(lineage_df["K"].mean()),
                "median_K": float(lineage_df["K"].median()),
                "prop_K_gt_1": float(np.mean(lineage_df["K"] > 1.0)),
                "mean_omega": float(lineage_df["omega"].mean()),
                "mean_filter_F": float(lineage_df["filter_F"].mean()),
                "mean_sweeps": float(lineage_df["sweep_count"].mean()),
                "n_pairs_used": int(len(degraded)),
            })
            all_summaries.append(summary)

    summary_df = pd.DataFrame(all_summaries)
    summary_df.to_csv(outdir / "scenario_summary_by_replicate.csv", index=False)

    # Aggregate numerical columns.
    group_cols = ["alpha", "psi", "architecture", "data_structure"]
    numeric_cols = [c for c in summary_df.columns if c not in group_cols and pd.api.types.is_numeric_dtype(summary_df[c])]
    aggregate = summary_df.groupby(group_cols)[numeric_cols].agg(["mean", "std"]).reset_index()
    aggregate.columns = ["_".join([str(x) for x in col if x]) for col in aggregate.columns.to_flat_index()]
    aggregate.to_csv(outdir / "scenario_summary_aggregated.csv", index=False)

    print(f"Wrote outputs to: {outdir}")
    print("Key files:")
    print(f"  {outdir / 'demo_lineages.csv'}")
    print(f"  {outdir / 'demo_pairs_full.csv'}")
    print(f"  {outdir / 'scenario_summary_by_replicate.csv'}")
    print(f"  {outdir / 'scenario_summary_aggregated.csv'}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Simulate the ovule-gated passenger RI model.")
    parser.add_argument("--outdir", default="results_demo", help="Output directory")
    parser.add_argument("--seed", type=int, default=12345, help="Random seed")
    parser.add_argument("--n_tips", type=int, default=80, help="Number of species tips")
    parser.add_argument("--n_reps", type=int, default=20, help="Replicates per parameter combination")
    parser.add_argument("--quick", action="store_true", help="Run a small demonstration grid")
    parser.add_argument("--pollen_c", type=float, default=300.0, help="Scaling constant for pollen production")
    parser.add_argument("--recombination", type=float, default=0.01, help="Recombination parameter for linked architecture")
    parser.add_argument("--pleiotropy", type=float, default=0.75, help="Pleiotropic coupling parameter")
    parser.add_argument("--alphas", type=float, nargs="+", default=[0.25, 0.5, 0.75, 1.0, 1.25])
    parser.add_argument("--psis", type=float, nargs="+", default=[0.001, 0.003, 0.01, 0.02, 0.05, 0.10])
    parser.add_argument("--architectures", nargs="+", default=["independent", "linked", "pleiotropic"])
    parser.add_argument(
        "--data_structures",
        nargs="+",
        default=["dense_reciprocal", "sparse_reciprocal", "pi_pairs", "one_direction", "summary_only"],
    )
    return parser.parse_args()


if __name__ == "__main__":
    run_grid(parse_args())
